### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by cyrilsuzat** [Simbul/semaphoreapp#4]
The Semaphore domain name changed :
https://semaphoreci.com/blog/2015/03/09/we-moved-from-semaphoreappcom-to-semaphorecicom.html

The API calls now return a "301 Moved Permanently"

```
> Semaphoreapp::Project.all

JSON::ParserError: 784: unexpected token at '<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.8.0</center>
</body>
</html>
```

**Comment by cyrilsuzat** [comment]
@Simbul  Can you please release a new version of the gem (0.2.1 ?)

**Comment by Simbul** [comment]
Done now :smiley:
Thanks for reminding me!
